### ISSUE TITLE
파이썬에서 디비 연결 

### ISSUE THREAD

**Issue by chchoco** [sangeuni/mondi-ssokssok#1]
mongodb에서 접속을 거부함

**Comment by chanmiJu** [comment]
xshell에서 
sudo /etc/mongod.conf 입력
포트를 0.0.0.0으로 수정
(0.0.0.0은 모든 ip에서 접근가능하다는것을 의미)

**Comment by chchoco** [comment]
xshell에서 
sudo /etc/mongod.conf 입력
포트를 0.0.0.0으로 수정
(0.0.0.0은 모든 ip에서 접근가능하다는것을 의미)
